---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stan.name" . }}-config
  labels:
    app: {{ template "stan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
stringData:
  stan.conf: |-
    http: 8222

    streaming {
      {{- with .Values.stan.nats.url }}
      ns: {{ . }}
      {{- end }}

      {{- if .Values.stan.clusterID }}
      id: {{ .Values.stan.clusterID }}
      {{- else }}
      id: {{ template "stan.name" . }}
      {{- end }}

      {{- with .Values.store.ft.group }}
      ft_group_name: {{ . }}
      {{- end }}

      {{- if eq .Values.store.type "sql" }}
      store: "sql"
      sql_options {
        driver: {{ .Values.store.sql.driver }}
        source: {{ tpl .Values.store.sql.source . | quote }}
      }
      {{- else if eq .Values.store.type "memory" }}
      store: "memory"
      {{- else }}
      store: "file"
      dir: {{ .Values.store.file.path }}
      {{- end  }}

      {{- if .Values.store.cluster.enabled }}
      cluster {
        node_id: $POD_NAME
        {{- with .Values.store.cluster.logPath }}
        log_path: {{ . }}
        {{- end }}

        # Explicit names of resulting peers
        peers: [
          {{ template "stan.clusterPeers" . }}
        ]
      }
      {{- end }}

      {{- with .Values.store.limits }}
      store_limits: {{ toPrettyJson . | indent 6 }}
      {{- end }}
    }
