{{- if eq .Values.store.type "sql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stan.name" . }}
  labels:
    app: {{ template "stan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}

stringData:
  dbUser: {{ .Values.store.sql.dbUser | quote }}
  dbPassword: {{ .Values.store.sql.dbPassword | quote }}
  sqlSource: {{ tpl .Values.store.sql.source . | quote }}
  dbManageUser: {{ .Values.store.sql.createdb.dbManageUser | quote }}
  dbManagePassword: {{ .Values.store.sql.createdb.dbManagePassword | quote }}
{{- end }}
