---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "stan.name" . }}
  labels:
    app: {{ template "stan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ template "stan.name" . }}

  {{- if .Values.store.cluster.enabled }}
  replicas: 3
  {{- else }}
  replicas: 1
  {{- end }}

  # NATS Streaming service name
  serviceName: {{ template "stan.name" . }}

  template:
    metadata:
      annotations:
        # see https://helm.sh/docs/charts_tips_and_tricks/#automatically-roll-deployments-when-configmaps-or-secrets-change
        checksum/{{ template "stan.name" . }}-config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        app: {{ template "stan.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - secret:
          secretName: {{ template "stan.name".  }}-config
        name: config-volume
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "stan.name" . }}
            topologyKey: kubernetes.io/hostname
{{- with .Values.affinity }}
{{ toYaml . | indent 8 }}
{{- end }}
      {{ $initDb := and (eq .Values.store.type "sql") (eq .Values.store.sql.driver "postgres") .Values.store.sql.initdb.enabled}}
      {{- if or .Values.initContainers $initDb }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if $initDb }}
      {{- if .Values.store.sql.initdb.enabled }}
        - name: init-database
          image: {{ .Values.store.sql.initdb.image }}
          env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbUser
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbPassword
          command: ['psql']
          args: [
          '--host', '{{ .Values.store.sql.dbHost }}',
          '-d', '{{ .Values.store.sql.dbName }}',
          '-p', '{{ .Values.store.sql.dbPort }}',
          '-c', 'CREATE TABLE IF NOT EXISTS ServerInfo (uniquerow INTEGER DEFAULT 1, id VARCHAR(1024), proto BYTEA, version INTEGER, PRIMARY KEY (uniquerow));
          CREATE TABLE IF NOT EXISTS Clients (id VARCHAR(1024), hbinbox TEXT, PRIMARY KEY (id));
          CREATE TABLE IF NOT EXISTS Channels (id INTEGER, name VARCHAR(1024) NOT NULL, maxseq BIGINT DEFAULT 0, maxmsgs INTEGER DEFAULT 0, maxbytes BIGINT DEFAULT 0, maxage BIGINT DEFAULT 0, deleted BOOL DEFAULT FALSE, PRIMARY KEY (id));
          CREATE INDEX IF NOT EXISTS Idx_ChannelsName ON Channels (name(256));
          CREATE TABLE IF NOT EXISTS Messages (id INTEGER, seq BIGINT, timestamp BIGINT, size INTEGER, data BYTEA, CONSTRAINT PK_MsgKey PRIMARY KEY(id, seq));
          CREATE INDEX IF NOT EXISTS Idx_MsgsTimestamp ON Messages (timestamp);
          CREATE TABLE IF NOT EXISTS Subscriptions (id INTEGER, subid BIGINT, lastsent BIGINT DEFAULT 0, proto BYTEA, deleted BOOL DEFAULT FALSE, CONSTRAINT PK_SubKey PRIMARY KEY(id, subid));
          CREATE TABLE IF NOT EXISTS SubsPending (subid BIGINT, row BIGINT, seq BIGINT DEFAULT 0, lastsent BIGINT DEFAULT 0, pending BYTEA, acks BYTEA, CONSTRAINT PK_MsgPendingKey PRIMARY KEY(subid, row));
          CREATE INDEX IF NOT EXISTS Idx_SubsPendingSeq ON SubsPending (seq);
          CREATE TABLE IF NOT EXISTS StoreLock (id VARCHAR(30), tick BIGINT DEFAULT 0);
          ALTER TABLE Clients ADD IF NOT EXISTS proto BYTEA;'
          ]
     {{- end }}
     {{- end }}
     {{- end }}
      containers:
        - name: stan
          image: {{ .Values.stan.image }}
          args:
            - --stan_config
            - /etc/stan-config/stan.conf
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 8222
            name: monitor
          - containerPort: 7777
            name: metrics
          volumeMounts:
          - name: config-volume
            mountPath: /etc/stan-config
          {{- if eq .Values.store.type "file"}}
          - name: {{ template "stan.name" . }}-pvc
            mountPath: {{ .Values.store.file.path }}
          {{- end }}
        {{ if .Values.exporter.enabled }}
        - name: metrics
          image: {{ .Values.exporter.image }}
          args:
          - -connz
          - -routez
          - -subz
          - -varz
          - -channelz
          - -serverz
          - http://localhost:8222/
          ports:
          - containerPort: 7777
            name: metrics
        {{ end }}
  {{- if eq .Values.store.type "file"}}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "stan.name" . }}-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.store.file.storageSize }}
  {{- end }}
