---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "stan.name" . }}
  labels:
    app: {{ template "stan.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app: {{ template "stan.name" . }}

  {{- if .Values.store.cluster.enabled }}
  replicas: 3
  {{- else }}
  replicas: 1
  {{- end }}

  # NATS Streaming service name
  serviceName: {{ template "stan.name" . }}

  template:
    metadata:
      annotations:
        # see https://helm.sh/docs/charts_tips_and_tricks/#automatically-roll-deployments-when-configmaps-or-secrets-change
        checksum/{{ template "stan.name" . }}-config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        app: {{ template "stan.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - secret:
          secretName: {{ template "stan.name".  }}-config
        name: config-volume
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ template "stan.name" . }}
            topologyKey: kubernetes.io/hostname
{{- with .Values.affinity }}
{{ toYaml . | indent 8 }}
{{- end }}
      {{ $usePostgres := and (eq .Values.store.type "sql") (eq .Values.store.sql.driver "postgres") }}
      {{- if or .Values.initContainers $usePostgres }}
      initContainers:
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if $usePostgres }}
        - name: wait-for-postgres
          image: appropriate/curl
          imagePullPolicy: IfNotPresent
        {{- with .Values.store.sql }}
          command:
            - sh
            - -c
            - |
              until [ $(curl {{ .dbHost }}:{{ .dbPort }} --silent; echo $?) = 52 ]; do
                echo "Waiting for {{ .dbHost }}"
                sleep 2
              done
        {{- end }}
        {{- if .Values.store.sql.createdb.enabled }}
        - name: create-database
          image: {{ .Values.store.sql.createdb.image }}
          env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbManageUser
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbManagePassword
          - name : PGHOST
            value: {{ .Values.store.sql.dbHost | quote }}
          - name : PGPORT
            value: {{ .Values.store.sql.dbPort | quote }}
          - name: PGDATABASE
            value: {{ .Values.store.sql.createdb.defaultDatabase }} 
          - name: SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbPassword
          - name: SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbUser
          {{ with .Values.store.sql }}
          command:
            - sh
            - -c
            - |
              roleExists() {
                  psql -tc "SELECT 1 FROM pg_roles where rolname='${1:?Which role?}'" | grep -qw 1
              }
              dbExists() {
                psql -ltq | cut -d" " -f2 | grep -qw "${1:?Which db?}"
              }

              user=${SERVICE_DB_USER:?}
              password=${SERVICE_DB_PASSWORD:?}
              if ! roleExists "$user"; then
                  psql -c "CREATE USER $user WITH LOGIN PASSWORD '$password'" > /dev/null
                  echo "Created database user '$user'"
              else
                  psql -c "ALTER USER $user WITH LOGIN PASSWORD '$password'" > /dev/null
                  echo "Updated password for database user '$user'"
              fi

              dbName={{ .dbName }}
              if ! dbExists "$dbName"; then
                  psql -tc "CREATE DATABASE $dbName OWNER $SERVICE_DB_USER" > /dev/null
                  echo "Created database '$dbName'"
              fi
        {{- end }}
        {{- end }}
        {{- if .Values.store.sql.initdb.enabled }}
        - name: init-database
          image: {{ .Values.store.sql.initdb.image }}
          env:
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbUser
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "stan.name" . }}
                key: dbPassword
          command: ['psql']
          args: [
          '--host', '{{ .Values.store.sql.dbHost }}',
          '-d', '{{ .Values.store.sql.dbName }}',
          '-p', '{{ .Values.store.sql.dbPort }}',
          '-c', 'CREATE TABLE IF NOT EXISTS ServerInfo (uniquerow INTEGER DEFAULT 1, id VARCHAR(1024), proto BYTEA, version INTEGER, PRIMARY KEY (uniquerow));
          CREATE TABLE IF NOT EXISTS Clients (id VARCHAR(1024), hbinbox TEXT, PRIMARY KEY (id));
          CREATE TABLE IF NOT EXISTS Channels (id INTEGER, name VARCHAR(1024) NOT NULL, maxseq BIGINT DEFAULT 0, maxmsgs INTEGER DEFAULT 0, maxbytes BIGINT DEFAULT 0, maxage BIGINT DEFAULT 0, deleted BOOL DEFAULT FALSE, PRIMARY KEY (id));
          CREATE INDEX IF NOT EXISTS Idx_ChannelsName ON Channels (name(256));
          CREATE TABLE IF NOT EXISTS Messages (id INTEGER, seq BIGINT, timestamp BIGINT, size INTEGER, data BYTEA, CONSTRAINT PK_MsgKey PRIMARY KEY(id, seq));
          CREATE INDEX IF NOT EXISTS Idx_MsgsTimestamp ON Messages (timestamp);
          CREATE TABLE IF NOT EXISTS Subscriptions (id INTEGER, subid BIGINT, lastsent BIGINT DEFAULT 0, proto BYTEA, deleted BOOL DEFAULT FALSE, CONSTRAINT PK_SubKey PRIMARY KEY(id, subid));
          CREATE TABLE IF NOT EXISTS SubsPending (subid BIGINT, row BIGINT, seq BIGINT DEFAULT 0, lastsent BIGINT DEFAULT 0, pending BYTEA, acks BYTEA, CONSTRAINT PK_MsgPendingKey PRIMARY KEY(subid, row));
          CREATE INDEX IF NOT EXISTS Idx_SubsPendingSeq ON SubsPending (seq);
          CREATE TABLE IF NOT EXISTS StoreLock (id VARCHAR(30), tick BIGINT DEFAULT 0);
          ALTER TABLE Clients ADD IF NOT EXISTS proto BYTEA;'
          ]
     {{- end }}
     {{- end }}
     {{- end }}
      containers:
        - name: stan
          image: {{ .Values.stan.image }}
          args:
            - --stan_config
            - /etc/stan-config/stan.conf
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 8222
            name: monitor
          - containerPort: 7777
            name: metrics
          volumeMounts:
          - name: config-volume
            mountPath: /etc/stan-config
          {{- if eq .Values.store.type "file"}}
          - name: {{ template "stan.name" . }}-pvc
            mountPath: {{ .Values.store.file.path }}
          {{- end }}
        {{ if .Values.exporter.enabled }}
        - name: metrics
          image: {{ .Values.exporter.image }}
          args:
          - -connz
          - -routez
          - -subz
          - -varz
          - -channelz
          - -serverz
          - http://localhost:8222/
          ports:
          - containerPort: 7777
            name: metrics
        {{ end }}
  {{- if eq .Values.store.type "file"}}
  volumeClaimTemplates:
  - metadata:
      name: {{ template "stan.name" . }}-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.store.file.storageSize }}
  {{- end }}
