apiVersion: v1
entries:
  stan:
  - apiVersion: v2
    appVersion: 0.17.0
    created: "2020-05-14T12:10:08.603095748+02:00"
    description: A Helm chart for NATS Streaming
    digest: f219cb040717f622bde37a65ab0b87fdc55d253e84df6a91794a5dbc16a9073d
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - streaming
    - stan
    - delivery
    - ratelimit
    - replay
    - statefulset
    - cncf
    maintainers:
    - email: wally@nats.io
      name: Waldemar Quevedo
    - email: colin@nats.io
      name: Colin Sullivan
    - name: rchenzheng
    name: stan
    urls:
    - https://hnicke.github.io/k8s/helm/charts/fork-repo/stan-0.4.2.tgz
    version: 0.4.2
generated: "2020-05-14T12:10:08.602005065+02:00"
